#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path


@dataclass
class RunRow:
    ip: str
    folder: Path
    label: str
    start_utc: str | None
    seconds: int | None
    d_events: int | None
    d_in: int | None
    d_out: int | None


def read_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def parse_summary(summary_path: Path) -> tuple[int | None, int | None, int | None]:
    text = summary_path.read_text(encoding="utf-8", errors="replace")
    # Table rows like: | `events_total` | 6 |
    def find(metric: str) -> int | None:
        m = re.search(rf"\|\s*`{re.escape(metric)}`\s*\|\s*([-0-9]+)\s*\|", text)
        if not m:
            return None
        try:
            return int(m.group(1))
        except Exception:
            return None

    return find("events_total"), find("count_in"), find("count_out")


def collect(root: Path) -> list[RunRow]:
    rows: list[RunRow] = []
    for ip_dir in sorted([p for p in root.glob("*") if p.is_dir()]):
        ip = ip_dir.name
        for run_dir in sorted([p for p in ip_dir.glob("*") if p.is_dir()]):
            meta = read_json(run_dir / "meta.json")
            summary = run_dir / "summary.md"
            d_events, d_in, d_out = (None, None, None)
            if summary.exists():
                d_events, d_in, d_out = parse_summary(summary)
            label = str(meta.get("label") or run_dir.name)
            start_utc = meta.get("start_utc")
            seconds = meta.get("seconds")
            try:
                seconds_i = int(seconds) if seconds is not None else None
            except Exception:
                seconds_i = None
            rows.append(
                RunRow(
                    ip=ip,
                    folder=run_dir,
                    label=label,
                    start_utc=str(start_utc) if start_utc is not None else None,
                    seconds=seconds_i,
                    d_events=d_events,
                    d_in=d_in,
                    d_out=d_out,
                ),
            )
    return rows


def main() -> int:
    root = Path("Docs/auto/camera-tuning")
    root.mkdir(parents=True, exist_ok=True)
    rows = collect(root)

    out = root / "INDEX.md"
    lines: list[str] = []
    lines.append("# Camera tuning index (auto)")
    lines.append("")
    lines.append("Generated by `scripts/camera_tuning_index.py`.")
    lines.append("")
    lines.append("| Camera IP | Run | Start (UTC) | seconds | Δevents | Δin | Δout |")
    lines.append("|---|---|---|---:|---:|---:|---:|")
    for r in rows:
        # Make links relative to Docs/auto/camera-tuning/INDEX.md location.
        rel_summary = (r.folder / "summary.md").relative_to(root)
        run_link = f"[{r.folder.name}]({rel_summary.as_posix()})"
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{r.ip}`",
                    run_link,
                    f"`{r.start_utc}`" if r.start_utc else "",
                    str(r.seconds or ""),
                    str(r.d_events if r.d_events is not None else ""),
                    str(r.d_in if r.d_in is not None else ""),
                    str(r.d_out if r.d_out is not None else ""),
                ],
            )
            + " |",
        )
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
