#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any


RUN_RE = re.compile(r"^\d{8}T\d{6}Z_.+")


@dataclass(frozen=True)
class RunRow:
    run_id: str
    label: str
    imgsz: int | None
    epochs: int | None
    dataset: str | None
    best_epoch: int | None
    map5095: float | None
    map50: float | None
    precision: float | None
    recall: float | None


def _f(v: Any) -> float | None:
    try:
        return float(v)
    except Exception:
        return None


def _i(v: Any) -> int | None:
    try:
        return int(float(v))
    except Exception:
        return None


def parse_best_from_results_csv(results_csv: Path) -> dict[str, Any] | None:
    if not results_csv.exists():
        return None
    with results_csv.open("r", encoding="utf-8", errors="replace", newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)
    if not rows:
        return None

    key = "metrics/mAP50-95(B)" if "metrics/mAP50-95(B)" in rows[0] else None
    if key is None:
        for k in ("metrics/mAP50-95", "metrics/mAP50-95(M)"):
            if k in rows[0]:
                key = k
                break
    if key is None:
        return None

    best = max(rows, key=lambda r: _f(r.get(key)) or float("-inf"))
    return {
        "best_epoch": _i(best.get("epoch")),
        "mAP50-95": _f(best.get(key)),
        "mAP50": _f(best.get("metrics/mAP50(B)")),
        "precision": _f(best.get("metrics/precision(B)")),
        "recall": _f(best.get("metrics/recall(B)")),
    }


def parse_from_summary_md(summary_md: Path) -> dict[str, Any] | None:
    if not summary_md.exists():
        return None
    out: dict[str, Any] = {}
    for line in summary_md.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line.startswith("- "):
            continue
        try:
            k, v = line[2:].split(":", 1)
        except ValueError:
            continue
        out[k.strip()] = v.strip()
    if "epoch" in out:
        out["best_epoch"] = _i(out["epoch"])
    if "metrics/mAP50-95(B)" in out:
        out["mAP50-95"] = _f(out["metrics/mAP50-95(B)"])
    if "metrics/mAP50(B)" in out:
        out["mAP50"] = _f(out["metrics/mAP50(B)"])
    if "metrics/precision(B)" in out:
        out["precision"] = _f(out["metrics/precision(B)"])
    if "metrics/recall(B)" in out:
        out["recall"] = _f(out["metrics/recall(B)"])
    return out


def read_preflight(preflight_json: Path) -> dict[str, Any] | None:
    if not preflight_json.exists():
        return None
    try:
        return json.loads(preflight_json.read_text(encoding="utf-8"))
    except Exception:
        return None


def render_md(rows: list[RunRow]) -> str:
    lines = [
        "# YOLOv8 head — runs report",
        "",
        "This file is auto-generated by `scripts/yolo_runs_report.py`.",
        "",
        "| run_id | label | imgsz | epochs | dataset | best_epoch | mAP50-95 | mAP50 | P | R |",
        "|---|---|---:|---:|---|---:|---:|---:|---:|---:|",
    ]
    for r in rows:
        def fmt(v: float | None) -> str:
            return "" if v is None else f"{v:.5f}"

        def fmti(v: int | None) -> str:
            return "" if v is None else str(v)

        lines.append(
            "| "
            + " | ".join(
                [
                    r.run_id,
                    r.label,
                    fmti(r.imgsz),
                    fmti(r.epochs),
                    (r.dataset or ""),
                    fmti(r.best_epoch),
                    fmt(r.map5095),
                    fmt(r.map50),
                    fmt(r.precision),
                    fmt(r.recall),
                ]
            )
            + " |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--root",
        default="Docs/auto/ml-training/yolov8-head",
        help="Root folder with run docs (default: Docs/auto/ml-training/yolov8-head)",
    )
    ap.add_argument(
        "--out",
        default="Docs/auto/ml-training/yolov8-head/REPORT.md",
        help="Output markdown file (default: Docs/auto/ml-training/yolov8-head/REPORT.md)",
    )
    args = ap.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    root = (repo_root / args.root).resolve()
    out = (repo_root / args.out).resolve()

    if not root.exists():
        raise SystemExit(f"Root not found: {root}")

    rows: list[RunRow] = []
    for p in sorted(root.iterdir()):
        if not p.is_dir():
            continue
        if p.name == "antileak":
            continue
        if not RUN_RE.match(p.name):
            continue

        run_id = p.name
        label = run_id.split("_", 1)[1] if "_" in run_id else run_id

        preflight = read_preflight(p / "preflight.json")
        dataset = None
        if isinstance(preflight, dict):
            dataset = (
                preflight.get("paths", {}).get("dataset")
                if isinstance(preflight.get("paths"), dict)
                else None
            )

        summary = parse_from_summary_md(p / "results" / "summary.md")
        if summary is None:
            # fallback to Ultralytics run dir by convention
            run_dir = repo_root / "ml/yolov8_head_finetune/runs" / run_id
            summary = parse_best_from_results_csv(run_dir / "results.csv") or {}

        imgsz = None
        epochs = None
        args_yaml = p / "results" / "args.yaml"
        if args_yaml.exists():
            # tiny yaml parser for two numeric keys
            for line in args_yaml.read_text(encoding="utf-8", errors="replace").splitlines():
                if line.startswith("imgsz:"):
                    imgsz = _i(line.split(":", 1)[1].strip())
                if line.startswith("epochs:"):
                    epochs = _i(line.split(":", 1)[1].strip())

        rows.append(
            RunRow(
                run_id=run_id,
                label=label,
                imgsz=imgsz,
                epochs=epochs,
                dataset=dataset,
                best_epoch=_i(summary.get("best_epoch")),
                map5095=_f(summary.get("mAP50-95")),
                map50=_f(summary.get("mAP50")),
                precision=_f(summary.get("precision")),
                recall=_f(summary.get("recall")),
            )
        )

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_md(rows), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

